### ISSUE TITLE
Inconsistent logo gradient across different viewport sizes

### ISSUE THREAD

**Issue by gmittal** [ProjectCopilot/projectcopilot.github.io#23]
The logo should look something like this:
![how it should look](https://puu.sh/shmeZ/64b45cee14.png)

However, the gradient is not fixed for some reason and changes as the viewport size changes.

**500px**: 
![screen shot 2016-11-13 at 4 03 40 pm](https://cloud.githubusercontent.com/assets/2015126/20249983/d17e8006-a9ba-11e6-99ad-204bbcf1e750.png)

**220px**:
![screenshot](https://puu.sh/shmqn/b4dbce8d58.png)

**1280px**:
![screenshot](https://puu.sh/shmuj/0d9c8a79c7.png)

As you can see, there is a lot of variance. Should be a fairly easy CSS fix. @srustagi can you take a look at this?

**Comment by gmittal** [comment]
The designer gave me this gradient code. It doesn't work as well as it should. I'm not super familiar with gradients in CSS3. 

``` css
#logo {
  background: -webkit-linear-gradient(180deg, #2ED157, #2E57D1);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
```
